// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fecxarphwirgzcbnrkjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlY3hhcnBod2lyZ3pjYm5ya2psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODM5MDIsImV4cCI6MjA3MzY1OTkwMn0.dHAy2n2VhpdDUdcrdYBRbBvjgdglT5QbHR0NxIBWa_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});